### ISSUE TITLE
IDNA v3.2 not compatible with Requests 2.25.1

### ISSUE THREAD

**Issue by BlueSkyTrading** [kjd/idna#101]
What changes have been added into idna > v2.5 that makes it incompatible with requests v2.25.1?

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. 
This behaviour is the source of the following dependency conflicts.
requests 2.25.1 requires idna<3,>=2.5, but you have idna 3.2 which is incompatible.
```

**Comment by kjd** [comment]
The only potential breaking change is dropping Python 2 support. idna<3 supports Python 2, idna 3.0 onward does not.

**Comment by kjd** [comment]
I'll also add the latest 2.x release v2.10 is functionally identical to v3.2. When the next edition of the Unicode standard is issued later this year, it is possible any updates can be backported to 2.x also if there is demand.
