### ISSUE TITLE
Potential inconsistency after decode/encode

### ISSUE THREAD

**Issue by pventuzelo** [kjd/idna#113]
Hey,

During fuzzing, I triggered this case where the result after decoding and encoding is different. I'm not familiar with IDNA so I don't know if it's expected or not.

## reproducer

``` python
import idna

data = b'Xn---00XA'
res = idna.decode(data)
data2 = idna.encode(res)

if data.upper() != data2.upper():
    print(data.upper())
    print(data2.upper())
    raise Exception('decode/encode')
```

## Result
``` sh
python3 replay_crash3.py
b'XN---00XA'
b'XN--00XA'
Traceback (most recent call last):
  File "replay_crash3.py", line 10, in <module>
    raise Exception('decode/encode')
Exception: decode/encode
```

**Comment by kjd** [comment]
Xn---00XA is not a legal U-label, but IDNA is being somewhat fault-tolerant and treating it as xn--00xa. I think the only potential argument is it should produce an error instead of successfully decoding it.

**Comment by kjd** [comment]
Will leave as-is for now.
