### ISSUE TITLE
implement UTS46

### ISSUE THREAD

**Issue by jribbens** [kjd/idna#12]
I have implemented UTS46, please see https://github.com/jribbens/idna

It passes 100% of the tests in IdnaTest.txt, except 34 which all contain 0x200c or 0x200d. I don't know what the problem is with those tests.

Can you pull this please?

**Comment by kjd** [comment]
Duplicates #7

**Comment by kjd** [comment]
Have merged this into the master. Will take a further look and try and identify the ZWJ/ZWNJ issue with the unit test. 

Thanks for the great work!

**Comment by kjd** [comment]
I've made a few patches to the tests, but fundamentally they key tests only execute in Python 3.4, due to the use of unittest.subTest. I think to put this into a published release the test runner needs to be refactored to work with Python 2.7, and other Python builds if possible.

**Comment by jribbens** [comment]
OK if you pull my latest changes from https://github.com/jribbens/idna I have made both the code and the tests support Python 2.7. Python 2.6 support might be a little more tricky though. Python 2.7 (wide) fails the same 34 tests as Python 3.4 does, and also skips 112 tests due to its unicodedata being older. Python 2.7 (narrow) should in theory also pass the tests, but skip more, but I have not been able to test this.

**Comment by kjd** [comment]
Thanks for this. By the way I looked briefly at the tests that were failing in Python 3.4. Line 525 and a few others fail on the U+20D8 character, not the ZWJ/ZWNJ, as U+20D8 is not PVALID in IDNA 2008. I am not sure if the lack of NV8 in the IdnaTest.txt is an error in the Unicode test suite for those lines, or I'm missing something else. Haven't had the opportunity to investigate further yet.

**Comment by kjd** [comment]
OK, have merge jribbens/master with master. Here is the latest build logs:

https://travis-ci.org/kjd/idna/builds/61407588

**Comment by jribbens** [comment]
Hmm does Travis' output really not show you which tests failed? That seems... suboptimal. I am investigating further into the 34 tests that I know to fail.

**Comment by jribbens** [comment]
Ok, I've done some more work on this. Now all tests pass on 2.7 and 3.3 and 3.4.

What I did was:

  * Strip leading empty labels on encode and decode (e.g. `...example.com` -> `example.com`).
    The `IdnaTest.txt` file seems to be expecting this behaviour, and Chrome does it too.
    Empty labels in the middle of the domain (e.g. `example...com`) will still produce an error.
  * Hard-code 12 tests to pretend they have the `NV8` flag set. As far as I can tell, the `IdnaTest.txt`
    file is simply wrong for these tests, they contain characters that RFC 5892 says are invalid and
    which are not replaced or removed by the UTS46 mapping.

There are 119 tests that Python 2 skips because its Unicode support is too old.

Note that the tests will not work on Python 2.6 because it does not support the test loading protocol, nor skipping tests. I think the code itself may well work though. I have made a fix for issue #15 as it was trivial.

**Note**: I have not made any changes to `codec.py`, so `IncrementalEncoder` and `IncrementalDecoder` will not produce the same results as any of the other methods. I am not sure why these methods don't just call `core.encode()` and `core.decode()` though.

**Comment by kjd** [comment]
Thanks for all your commits, they are greatly appreciated. They've been all placed into a new release v2.0 which is now on PyPI.

Will look into supporting it for the codec functions, whether there are corner cases that the incremental encoding methods trying with encode()/decode() will not catch.
