### ISSUE TITLE
Continuous fuzzing by way of OSS-Fuzz

### ISSUE THREAD

**Issue by DavidKorczynski** [kjd/idna#122]
Hi,

I was wondering if you would like to integrate continuous fuzzing by way of OSS-Fuzz? Fuzzing is a way to automate test-case generation and can be used to find unexpected exceptions in Python. In this PR https://github.com/google/oss-fuzz/pull/8264 I did an initial integration into OSS-Fuzz and the [current fuzzer](https://github.com/google/oss-fuzz/pull/8264/files#diff-5e233304fc89e28ec1f7fb6b3689be57f2657fd0ca69d5bf31eda309ba8ab114) targets the decode and encode apis. The fuzzing engine used by OSS-Fuzz is [Atheris](https://github.com/google/atheris).

If you would like to integrate, the only thing I need is a list of email(s) that will get access to the data produced by OSS-Fuzz, such as bug reports, coverage reports and more stats. Notice the emails affiliated with the project will be public in the OSS-Fuzz repo, as they will be part of a configuration file.

**Comment by kjd** [comment]
Sure, that works for me. Best email address for me for this project would be kim@cynosure.com.au
