### ISSUE TITLE
Found a bug in idna version 2.8:UnicodeEncodeError: 'ascii' codec can't encode character '\uff2a' in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by aT0ngMu** [kjd/idna#137]
Hi,I found a bug in idna version 2.8, when a byte-type input is provided to the encode function defined in the Codec class, the function calls the encode function in core.py, and the ascii decoder cannot decode the byte-type input.

The following is the stack information:
 === Uncaught Python exception: ===
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8e in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "codec_driver.py", line 24, in TestOneInput
    encode_data = instance.encode(data=input_bytes, errors="strict")
  File "/usr/lib/python3/dist-packages/idna/codec.py", line 17, in encode
    return encode(data), len(data)
  File "/usr/lib/python3/dist-packages/idna/core.py", line 343, in encode
    s = s.decode("ascii")
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8e in position 0: ordinal not in range(128)

The following is the test case that triggers the crash.
[t.zip](https://github.com/kjd/idna/files/10799793/t.zip)

**Comment by jribbens** [comment]
Your attached file is a zip containing nothing but a 1-byte file. Please provide a test case in a comment to the issue.

Having said that, it sounds like what you're doing is just wrong - trying to "encode" a byte-string is a contradiction in terms. The error message returned from the module should be telling you this.

**Comment by aT0ngMu** [comment]
I'm sorry about attached file.The test case is é.

**Comment by jribbens** [comment]
You can pass a byte type... if it's ASCII. If it isn't, you need to pass a string.
