### ISSUE TITLE
CI: Set minimum permissions on GitHub Workflow

### ISSUE THREAD

**Issue by diogoteles08** [kjd/idna#139]
Hello!

I'd like to suggest the definition of minimal permissions on your [python-package.yml](https://github.com/kjd/idna/blob/master/.github/workflows/python-package.yml) workflow, as it would harden your security agains supply-chain attacks.

I see that on your other workflow, [deploy.yml](https://github.com/kjd/idna/blob/master/.github/workflows/deploy.yml), you have already defined a top-level read-only permission, and the idea would be to do the same with the other workflow. The ideal is to set a top-level restrictive permission, and add any other needed permissions as job-level permissions. 

Setting minimum permissions for workflows is recommended by [GitHub itself](https://docs.github.com/en/actions/security-guides/automatic-token-authentication) and also by other security tools, such as [Scorecards](https://github.com/ossf/scorecard) and [StepSecurity](https://github.com/step-security).

Let me know if you are interested and I'll be happy to raise a PR with the change.

#### Context
I'm Diogo and I work on Google's Open Source Security Team([GOSST](https://github.com/diogoteles08#about-gosst-ghost)) in cooperation with the Open Source Security Foundation ([OpenSSF](https://openssf.org/)). My core job is to suggest and implement security changes on widely used open source projects 😊

**Comment by sethmlarson** [comment]
Such a change sounds good to me, thanks @diogoteles08!

**Comment by diogoteles08** [comment]
Great! I'll be raising PR shortly
