### ISSUE TITLE
Exception when decoding U+20AC Euro Sign

### ISSUE THREAD

**Issue by vhnguyenae** [kjd/idna#146]
Hi, 
I'm trying to decode `xn--punycode-fk-u8a3886h9p1r.com` using:
`print(idna.decode('xn--punycode-fk-u8a3886h9p1r.com'))`
but I got this error below
```
/idna/core.py", line 250, in check_label
    raise InvalidCodepoint('Codepoint {} at position {} of {} not allowed'.format(_unot(cp_value), pos+1, repr(label)))
idna.core.InvalidCodepoint: Codepoint U+20AC at position 13 of 'punycode-fäk€页' not allowed
```
But it looks like a valid punny code as I can decode it on https://encode-decode.com/punycode-decode-online/
`http://xn--punycode-fk-u8a3886h9p1r.com` --> `http://punycode-fäk€页.com`

Can you check why? It looks like a valid code for me.
Thank you in advance

**Comment by jribbens** [comment]
20AC EURO SIGN is disallowed by the IDNA 2008 rules. The error message is correct.
```
20A0..20B8  ; DISALLOWED  # EURO-CURRENCY SIGN..TENGE SIGN
```
https://www.rfc-editor.org/rfc/rfc5892.html#page-51
