### ISSUE TITLE
Please consider to upload a wheel to PyPI

### ISSUE THREAD

**Issue by hynek** [kjd/idna#16]
Hi,

it would be great if you could upload a wheel of idna to PyPI which install much faster.

The current version of pip does it automatically but it would be nice if I could skip this step. :)

If you need any help, https://hynek.me/articles/sharing-your-labor-of-love-pypi-quick-and-dirty/ should get you started.

Thanks!

**Comment by kjd** [comment]
OK this has been done. Thanks!

**Comment by hynek** [comment]
Thank you!
