### ISSUE TITLE
PyPI Publish GitHub Action failing

### ISSUE THREAD

**Issue by kjd** [kjd/idna#163]
While I expect it to fail (credentials for PyPI haven't been supplied yet), I don't expect it to fail the way it did:

> [Invalid workflow file: .github/workflows/deploy.yml#L12](https://github.com/kjd/idna/actions/runs/6983769931/workflow)
> The workflow is not valid. .github/workflows/deploy.yml (Line: 12, Col: 3): Unexpected value 'content'

**Comment by elliotwutingfeng** [comment]
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions

Appears to be `contents` now?
