### ISSUE TITLE
Document exceptions

### ISSUE THREAD

**Issue by jpgoldberg** [kjd/idna#171]
Your package does a great[^123] job at validating hostnames, which is something I've been working on. And, indeed, I could just wrap `encode()`  as a hostname validator, but I would need some guarantees as to what raises what exceptions.

And so, I would like the exceptions raised to be documented features instead of something that I can't rely on given the current state of the documentation.

[^123]: The one place I've seen that `encode()` isn't a complete hostname validator is that it doesn't check whether the rightmost label is all digits.  "`this.is.123.good`", but "`this.should.be.bad.123`"

**Comment by kjd** [comment]
The current exceptions are documents, while briefly, at https://github.com/kjd/idna/blob/master/README.rst#exceptions

If you have specific suggestions on expanding the documentation it is welcome.

**Comment by jpgoldberg** [comment]
Thank you. I seem to have missed that. I will close this issue. I may return with a PR of expanded documentation, but I can't promise to do so.
