### ISSUE TITLE
Tests fail on Python 2.6

### ISSUE THREAD

**Issue by rbu** [kjd/idna#20]
Is idna supposed to work on Python 2.6? The documentation does not explicitly state that 2.7 is required and 2.6 is not. There has been at least one commit to improve 2.6 compat as well.

I've added to obvious fxes to the tests for 2.6 that, but I'm not exactly sure what the correct fix for the two remaining tests is.

Patch:

``` diff
diff --git a/tests/test_idna_codec.py b/tests/test_idna_codec.py
index fe3737a..2d0cd14 100755
--- a/tests/test_idna_codec.py
+++ b/tests/test_idna_codec.py
@@ -24,7 +24,7 @@ class IDNACodecTests(unittest.TestCase):
         )

         for decoded, encoded in incremental_tests:
-            if sys.version_info.major == 2:
+            if sys.version_info[0] == 2:
                 self.assertEqual("".join(codecs.iterdecode(encoded, "idna")),
                                 decoded)
             else:
diff --git a/tests/test_idna_uts46.py b/tests/test_idna_uts46.py
index d8a2836..c93c0df 100755
--- a/tests/test_idna_uts46.py
+++ b/tests/test_idna_uts46.py
@@ -51,6 +51,8 @@ class TestIdnaTest(unittest.TestCase):
         return "%s.%d" % (super(TestIdnaTest, self).id(), self.lineno)

     def shortDescription(self):
+        if not self.fields:
+            return ""
         return "IdnaTest.txt line %d: %r" % (self.lineno,
             u"; ".join(self.fields))

```

Failures:

``` shell
======================================================================
ERROR: test_decode (tests.test_idna.IDNATests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rbu/devel/code/idna/tests/test_idna.py", line 258, in test_decode
    self.assertEqual(idna.decode('xn---------90gglbagaar.aa'),
  File "/home/rbu/devel/code/idna/idna/core.py", line 383, in decode
    result.append(ulabel(label))
  File "/home/rbu/devel/code/idna/idna/core.py", line 302, in ulabel
    check_label(label)
  File "/home/rbu/devel/code/idna/idna/core.py", line 254, in check_label
    check_bidi(label)
  File "/home/rbu/devel/code/idna/idna/core.py", line 70, in check_bidi
    raise IDNABidiError('Unknown directionality in label {0} at position {1}'.format(repr(label), idx))
IDNABidiError: Unknown directionality in label u'\u0521\u0525\u0523-\u0523\u0523-----\u0521\u0523\u0523\u0523' at position 2

======================================================================
ERROR: test_encode (tests.test_idna.IDNATests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rbu/devel/code/idna/tests/test_idna.py", line 244, in test_encode
    self.assertEqual(idna.encode(u'\u0521\u0525\u0523-\u0523\u0523-----\u0521\u0523\u0523\u0523.aa'),
  File "/home/rbu/devel/code/idna/idna/core.py", line 354, in encode
    result.append(alabel(label))
  File "/home/rbu/devel/code/idna/idna/core.py", line 275, in alabel
    check_label(label)
  File "/home/rbu/devel/code/idna/idna/core.py", line 254, in check_label
    check_bidi(label)
  File "/home/rbu/devel/code/idna/idna/core.py", line 70, in check_bidi
    raise IDNABidiError('Unknown directionality in label {0} at position {1}'.format(repr(label), idx))
IDNABidiError: Unknown directionality in label u'\u0521\u0525\u0523-\u0523\u0523-----\u0521\u0523\u0523\u0523' at position 2

----------------------------------------------------------------------
Ran 17 tests in 0.007s

FAILED (errors=2)
```

**Comment by kjd** [comment]
Support for Python 2.6 hasn't been a priority, but I have no problem adding it if it doesn't result in drastic code changes. Will analyse.

**Comment by kjd** [comment]
I think the remaining failures are nothing to do with the library having actual issues, or anything specific to Python 2.6's syntax, but rather that Python 2.6 is bundled with old Unicode data from v5.1.0 of the standard, which having been published in 2008 lacks information on newer codepoints that are in the test suite.

Probably the best short term solution is to detect the version of unicodedata from unicodedata.unidata_version and if it is older than what was used in tools/build-idnadata.py then it should raise a non-fatal warning in the test suite, and allow unknown codepoint errors to be skipped.

Longer term architectural question it raises is should we remove the dependency on the system provided unicodedata module and pull all the properties we need in separately. It is currently used to assess directionality, combining characters, category and to perform NFC normalization. The last one is presumably the most complicated to roll our own on.

**Comment by kjd** [comment]
Issue not identified by current tests:

build-idnadata.py fails on Python 2.6 as XPath's are not properly supported by xml.etree until Python 2.7. Does not affect operation of the module, but does mean a user of 2.6 can not rebuild idnadata.py from scratch.

**Comment by rbu** [comment]
Thanks for looking into this. I totally agree not investing too much energy into Python 2.6 support, especially when it means forking unicode data.
From what I understand, with this incomplete data set, the library raises an error when bidirectionality cannot be determined. Would it make sense to declare this expected behavior, i.e. on old Python systems, some idna names cannot be parsed? That way, only tests would have to be changed based on Python version.

**Comment by opoplawski** [comment]
Any more progress here in dealing with the old unicode data?

**Comment by kjd** [comment]
I am currently on travel which makes it a little difficult to work on, but I hope to push a new release to address this issue an the other open issues in the next few weeks. Patches are welcome, otherwise it will need to wait a little bit until I get some free time.

**Comment by rbu** [comment]
@kjd thanks for the fix
