### ISSUE TITLE
"codepoint not allowed" (with existing name)

### ISSUE THREAD

**Issue by romuald** [kjd/idna#25]
Hello

Given the string `u'\u2709'` (or the encoded form `xn--4bi`)

Trying to use encode / decode on that string will always raise the following error:

*Codepoint U+2709 at position 1 of u'\u2709' not allowed*

The domain in question exists and is resolving, the standard python idna module correctly encodes/decodes the string.

Is this an issue with idna module or am I missing something?

**Comment by kjd** [comment]
The library is implementing the specification correctly. 

In the current IDNA standard symbols like U+2709 are not allowed. This is one of the decisions made in the IETF and is a difference between IDNA 2003 and IDNA 2008. Invalid labels like these should not be used as they will grow increasingly incompatible with deployed software, and are no longer allowed in registry policies by ICANN.

**Comment by romuald** [comment]
Thanks for the explanation

(unfortunately those are domains that actually exists, so I'll have to find a way to handle them anyway :cry:)

**Comment by kjd** [comment]
You may wish to consider when doing Unicode->ASCII conversion, falling back to the 2003 spec (i.e. the Python built-in library) if this library (i.e. 2008 conversion) fails first. However, in the converse, for ASCII->Unicode, if the conversion fails, show it as ASCII. This allows users with deprecated domains to type them in, but does not give the false impression they are still valid domains; and allows people who use up-to-date software to cut and paste the invalid A-label and still access the domain.

Do consider the 2008 specification was driven by real security concerns (e.g. phishing attacks) and there is some risk in any approach that uses IDNA 2003. The UTS46 functionality is meant to provide a bridge for this for linguistic situations but doesn't help with symbols.
