### ISSUE TITLE
Codepoint U+2010 not allowed

### ISSUE THREAD

**Issue by GoldenStake** [kjd/idna#31]
```
>>> idna.encode("one‐two.com".decode("utf-8"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/idna/core.py", line 354, in encode
    result.append(alabel(label))
  File "/usr/lib/python2.7/dist-packages/idna/core.py", line 275, in alabel
    check_label(label)
  File "/usr/lib/python2.7/dist-packages/idna/core.py", line 252, in check_label
    raise InvalidCodepoint('Codepoint {0} at position {1} of {2} not allowed'.format(_unot(cp_value), pos+1, repr(label)))
idna.core.InvalidCodepoint: Codepoint U+2010 at position 4 of u'one\u2010two' not allowed
```

**Comment by kjd** [comment]
U+2010 is indeed not allowed by IDNA, i.e. p50 of [RFC 5892](https://tools.ietf.org/html/rfc5892):
`200E..2064  ; DISALLOWED  # LEFT-TO-RIGHT MARK..INVISIBLE PLUS`

In general, punctuation or other symbols are not permitted in IDNs by the standard. The hyphen-minus (resulting from the hyphen key on a particular keyboard) generates a U+002D character which is permitted, but other kinds of hyphens are not permitted.

Here is the string with a normal hyphen-minus from ASCII:

```
>>> idna.encode("one-two.com".decode("utf-8"))
'one-two.com'
```
