### ISSUE TITLE
Import error inside import hook.

### ISSUE THREAD

**Issue by llazzaro** [kjd/idna#35]
Hello,

I recently upgraded to requests 2.12 which uses idna and I started to see this import error:

> (Pdb) request('get', url, params=params, **kwargs)
> *** ImportError: No module named uts46data

Looking in the changes I saw that it was recently added idna. 
My projects are using import hooks and inside of it the hook use requests, which uses idna.

The code of idna is doing an import inside the method `uts46_remap`, which is breaking my code.
Moving the import uts46_remap outside fixes this issue.

**Comment by llazzaro** [comment]
check pull request here: https://github.com/kjd/idna/pull/34

**Comment by kjd** [comment]
By applying this change, it means over megabytes of data will need to be imported for each invocation for functionality that defaults to off and is likely not commonly used. The intent of having the import in the function is to only import the UTS 46 data if you are doing a UTS 46 conversion, and if you are only doing IDNA conversion you are not penalized. Given a number of patches I've received in the past are to do with reducing memory usage, I am hesitant to add a patch like this without further analysis.

Some quick numbers:

```
python -c 'import idna; idna.decode("xn--p1ai")'
Maximum resident set size (kbytes): 7608

python -c 'import idna; idna.decode("xn--p1ai", uts46=True)'
Maximum resident set size (kbytes): 9060
```

I am not sure I fully understand the use case around why this is a problem to begin with, but is there a patch that would address your issue and not require uts46data to be loaded unless you are using UTS46 functionality? (i.e. only import that data if uts46=True)

**Comment by kjd** [comment]
Also, can you provide a reduction of the problem so it can be added as a unit test? There is no 'request' method in this library so presumably that is from somewhere else.

**Comment by jribbens** [comment]
It looks like he's calling requests and requests is calling idna. To be honest it sounds like his environment is broken if standard 'import's aren't working. He could presumably work around the problem by calling `import idna.uts46data` at the start of his application so it's pre-loaded. A compromise solution might be to make that 'official' by adding a documented `idna.load_data()` function or something?

**Comment by llazzaro** [comment]
The issue was copied from requests library which uses idna (I edited the issue). I found this bug with the latest version of requests.
The problem is that when using import hooks (PEP302 with python2) you can't import inside a method, that will result with the import error.
I moved the import outside the method and everything is working fine.

doing a `import idna.uts46data` will work fine at the beginning of the file, however when the method is called uts46_remap the import error will be raised.

I will try to do an unit test to reproduce this issue

**Comment by jribbens** [comment]
This really sounds like a bug in your import hook rather than a bug in idna.

**Comment by llazzaro** [comment]
@kjd since moving the import means over megabytes of data will need. I will close this one since I found a way to avoid using the` uts46=True`.

@jribbens it's not a bug, I will not discuss this here...but you can't do an import inside a module loader or finder.
