### ISSUE TITLE
Overly restrictive rules for KATAKANA MIDDLE DOT

### ISSUE THREAD

**Issue by cornmander** [kjd/idna#46]
RFC5892 A.7 states that the KATAKANA MIDDLE DOT character https://tools.ietf.org/html/rfc5892#appendix-A.7 requires at least one character in the {Hiragana, Katakana, Han} scripts. The validation in this library requires that ALL characters in the label (besides the dot character itself) be in those scripts.

**Comment by cornmander** [comment]
As another datapoint, here's the ICANN LGR for Japanese:
https://www.icann.org/sites/default/files/packages/lgr/lgr-second-level-japanese-30aug16-en.html

Japanese in Label — restricts the occurrence of U+30FB (・) KATAKANA MIDDLE DOT to labels containing at least one code point from any of these scripts: Han, Hiragana, and Katakana. This rule is described in Appendix A.7 of RFC5892 [122]

**Comment by kjd** [comment]
Patch merged.
