### ISSUE TITLE
Failing domain 'xn--hjdarna07-b07a.cf'

### ISSUE THREAD

**Issue by szatkus** [kjd/idna#53]
Hi,

I found an instance of domain which cannot be decoded by IDNA library.

<pre>In [3]:  idna.decode('xn--hjdarna07-b07a.cf')

InvalidCodepoint                          Traceback (most recent call last)
<ipython-input-3-07b3c0da3e70> in <module>()
----> 1 idna.decode('xn--hjdarna07-b07a.cf')

/usr/local/lib/python2.7/dist-packages/idna/core.pyc in decode(s, strict, uts46, std3_rules)
    382         trailing_dot = True
    383     for label in labels:
--> 384         result.append(ulabel(label))
    385     if trailing_dot:
    386         result.append(u'')

/usr/local/lib/python2.7/dist-packages/idna/core.pyc in ulabel(label)
    301 
    302     label = label.decode('punycode')
--> 303     check_label(label)
    304     return label
    305 

/usr/local/lib/python2.7/dist-packages/idna/core.pyc in check_label(label)
    251                 raise InvalidCodepointContext('Codepoint {0} not allowed at position {1} in {2}'.format(_unot(cp_value), pos+1, repr(label)))
    252         else:
--> 253             raise InvalidCodepoint('Codepoint {0} at position {1} of {2} not allowed'.format(_unot(cp_value), pos+1, repr(label)))
    254 
    255     check_bidi(label)

InvalidCodepoint: Codepoint U+10A5 at position 7 of u'hjdarn\u10a5a07' not allowed</pre>

The excepted output is "hjdarnႥa07.cf". The domain exists (http://xn--hjdarna07-b07a.cf/) and is correct IDNA code (http://unicode.org/cldr/utility/idna.jsp?a=hjdarn%E1%82%A5a07.cf).

**Comment by kjd** [comment]
The domain is not a legal domain according to the IDNA standard. The library is performing correctly.

Here is diagnostic output for that code point from the idna-data tool just added in v2.6:

```
$ idna-data U+10A5
U+10A5:
   Name:             GEORGIAN CAPITAL LETTER VIN
1  Exceptions:       False
2  Backwards Compat: False
3  Unassigned:       False
4  LDH:              False
   Properties:       Alphabetic Cased Changes_When_Casefolded Changes_When_Casemapped Changes_When_Lowercased Grapheme_Base ID_Continue ID_Start Uppercase XID_Continue XID_Start
5  .Join Control:    False
   NFKC CF:          U+2D05
6  .Unstable:        True
7  .Ignorable Prop:  False
   Block:            Georgian
8  .Ignorable Block: False
   Hangul Syll Type: None
9  .Old Hangul Jamo: False
   General Category: Lu
10 .Letters Digits:  True
== IDNA 2008:        DISALLOWED
== UTS 46:           disallowed
(Unicode 6.3.0 [sys:9.0.0])
```

It is disallowed because it is unstable (its NFKC case folded form is U+2D05), and it is unstable on its face because it is a capital letter (all capital letters are prohibited in IDNA).

The link to the CLDR IDNA tool above shows it is illegal too (hence it is in red).
