### ISSUE TITLE
2.7 regression (A-label validation)

### ISSUE THREAD

**Issue by romuald** [kjd/idna#65]
Hello

We've encountered a regression with the 2.7 release and the additonal validation of A-labels

I'm not certain if should be fixed but I just wanted to let you know.

```python

# Context, handling of DNS records

host = u'*.foö.fi'

return {'host_ulabel' : host,
        'host_alabel' : idna.encode(host, uts46=True)}
```

Which now raises `idna.core.IDNAError: The label * is not a valid A-label`

**Comment by romuald** [comment]
Sorry I misinterpreted the problem.

The problem actually that the exception changed from `idna.core.InvalidCodepoint` to `idna.core.IDNAError`

**Comment by romuald** [comment]
I'm closing the issue (but I don't actually know if this is something you wish to change later)

**Comment by kjd** [comment]
Will investigate. While I don't think this is a bug I think the more specific exception is preferable.
