### ISSUE TITLE
Clarify future Python version support

### ISSUE THREAD

**Issue by sethmlarson** [kjd/idna#80]
This is mostly a question for @kjd. I saw the `py3-only` branch and was wondering when that branch is going to be released and I'm assuming as a "v3.0"? When the question is answered feel free to close this issue. Thanks!

**Comment by kjd** [comment]
Unicode 13 is expected to come out in around a month, once released that may be a good time for the next release.

Unless anyone has strong suggestions in another direction, I was thinking that would be a Python 3-only release and would be 3.0, retaining the possibility of backporting future fixes to version 2.x if warranted.
