### ISSUE TITLE
Document lowercase before encode?

### ISSUE THREAD

**Issue by JoshData** [kjd/idna#9]
Hello,

The change from IDNA 2003 to 2008 (and from Python's built-in codec to the `idna` module) is a bit complicated for application developers. Some documentation about application-level requirements before calling `encode` might be handy, i.e. [RFC 5895](http://www.ietf.org/rfc/rfc5895.txt) section 2. I'm just working through it now so I'm not sure if I understand it all correctly, but I've got:

>  1  Uppercase characters are mapped to their lowercase equivalents by
>       using the algorithm for mapping case in Unicode characters.  This
>       step was chosen because the output will behave more like ASCII
>       host names behave.

	domain = domain.lower()

>   2  Fullwidth and halfwidth characters (those defined with
>       Decomposition Types < wide > and < narrow >) are mapped to their
>       decomposition mappings as shown in the Unicode character
>       database.  This step was chosen because many input mechanisms,
>       particularly in Asia, do not allow you to easily enter characters
>       in the form used by IDNA2008.  Even if they do allow the correct
>       character form, the user might not know which form they are
>       entering.

	def wide_narrow(c):
		decomp = unicodedata.decomposition(c)
		m = re.match('<(?:narrow|wide)> ([A-Z0-9]+)$', decomp)
		if m:
			return chr_func(int(m.group(1), 16)) # chr in Py3, unichr in Py2
		return c

	domain = ''.join(wide_narrow(c) for c in domain)

>   3  All characters are mapped using Unicode Normalization Form C
>       (NFC).  This step was chosen because it maps combinations of
>       combining characters into canonical composed form.  As with the
>       fullwidth/halfwidth mapping, users are not generally aware of the
>       particular form of characters that they are entering, and
>       IDNA2008 requires that only the canonical composed forms from NFC
>       be used.

	domain = unicodedata.normalize("NFC", domain)

>   4  [IDNA2008protocol] is specified such that the protocol acts on
>       the individual labels of the domain name.  If an implementation
>       of this mapping is also performing the step of separation of the
>       parts of a domain name into labels by using the FULL STOP
>       character (U+002E), the IDEOGRAPHIC FULL STOP character (U+3002)
>       can be mapped to the FULL STOP before label separation occurs.
>       There are other characters that are used as "full stops" that one
>       could consider mapping as label separators, but their use as such
>       has not been investigated thoroughly.  This step was chosen
>       because some input mechanisms do not allow the user to easily
>       enter proper label separators.  Only the IDEOGRAPHIC FULL STOP
>       character (U+3002) is added in this mapping because the authors
>       have not fully investigated the applicability of other characters
>       and the environments where they should and should not be
>       considered domain name label separators.

	domain = domain.replace('\u3002', '.')

^ Seems to be handled by the `idna` module.

Does this look right?

Step 2 is a bit awkward so maybe this all can be incorporated into the module?

**Comment by jribbens** [comment]
Issue #12 is relevant to this I believe.

**Comment by kjd** [comment]
A new version, v2.0, has been released which adds Unicode compatibility mapping, which should address these types of issues in a simple way. Try using:

domain = idna.encode(domain, uts46=True)

**Comment by JoshData** [comment]
Amazing. I think that resolves it (and lets me delete application-level code --- see the commit referenced above). Thanks.
