### ISSUE TITLE
Latest version with Python 2.7 support?

### ISSUE THREAD

**Issue by ReenigneArcher** [kjd/idna#97]
I need to include idna in a project that cannot use anything greater than python 2.7.

I would like to download the source code for the last version supporting 2.7. Could you please let me know which one to use?

**Comment by sethmlarson** [comment]
The last version of `idna` to support Python 2.7 was [`2.10`](https://github.com/kjd/idna/blob/master/HISTORY.rst#210-2020-06-27) although if tools installing are compliant they should install the proper version of `idna` because of the `Requires-Python` directive.
