### ISSUE TITLE
Gracefully deprecate Python 2 support

### ISSUE THREAD

**Issue by kjd** [kjd/idna#98]
Version 3.0 deprecated Python 2 support, but it appears it had unexpected collateral impact. There was no intention to impact downstream users, with the basic approach being:

* held off for one additional year after Python 2 was formally deprecated, 
* provided 6 months advance notice in the changelog, and 
* major version bump to signal incompatibility with the last version.

This ticket is just to trace known issues and if any corrective action to this library would be beneficial.

**Comment by kjd** [comment]
https://github.com/psf/requests/issues/5710
https://github.com/psf/requests/pull/5711

**Comment by ViktorHaag** [comment]
It might be immediately beneficial to leave the last 2.x version of this project available on PyPi, as `requests` hasn't yet rolled a release to support idna 3.x, and I'm not sure how people can now install or re-build requests now that one of its pinned dependencies has a required version disappear...

**Comment by sethmlarson** [comment]
@ViktorHaag [The 2.x versions are still present and not yanked](https://pypi.org/project/idna/#history).

**Comment by ViktorHaag** [comment]
Yep; you are correct; I was looking at the wrong place mistakenly.

**Comment by BSVogler** [comment]
Python 2 is already not supported any more sice 1. jan 2020.

**Comment by kjd** [comment]
Closing as no further issues have emerged.
